# Generated by Django 5.1.1 on 2024-09-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ungdunggb', '0003_category_active_category_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_name',
            new_name='name',
        ),
    ]
