# Generated by Django 5.1.1 on 2024-10-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ungdunggb', '0010_cart_coupon_customer_remove_rating_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customers'},
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='postal_code',
        ),
    ]
