# Generated by Django 5.1.1 on 2024-10-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungdunggb', '0011_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('individual', 'Cá nhân'), ('group', 'Nhóm')], default='individual', max_length=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='ungdunggb.customer'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='group_buys',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='ungdunggb.groupbuy'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='ungdunggb.product'),
        ),
    ]
