"""
Django settings for duangb project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

from django.conf.global_settings import MEDIA_ROOT

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3i^cf4qw34+otq^e1-p*w2&!57qtnu_g8gfpdp*a%ass6m72zj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ungdunggb.apps.UngdunggbConfig',
    'ckeditor',
    'ckeditor_uploader',
    'debug_toolbar',
    'rest_framework',
    'drf_yasg',
    'cloudinary',
    'oauth2_provider',
]

# client ID: JP8d7Gi7bXqTskuexdkpLTxWLRbkR6tLFy89obmC
# client secret: cx8h6ItGxDOkYzrnVjvO2IyOw9VX0CXhxkx2RVCDy6YhX0wOeO6azr5EKhGeEaO9iwNU6FMEqdjcOUM9FZNSBbUeHQQEkJw8AyHOja0UAvkUFmp3re2mXiOzXy3qUgUn

# bien cau hinh api, dung lam chung thuc
# dung oauth2 chung thuc nen phai migrate de update table
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}


CKEDITOR_UPLOAD_PATH = "ckeditor/images/"

import cloudinary

cloudinary.config(
    cloud_name="dbqaequqv",
    api_key="741317942552615",
    api_secret="L05czfd2tdEhRvbUy29A1vF8BZ4"
)

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'duangb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        # 'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'duangb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'gbdb',
        'USER': 'chanh',
        'PASSWORD': 'Admin@123',
        'HOST': 'localhost',  #mac dinh local host
        'PORT': '5432',  # Cổng mặc định của PostgreSQL
    }
}

MEDIA_ROOT = '%s/ungdunggb/static/' % BASE_DIR

INTERNAL_IPS = [
    "127.0.0.1",
]

AUTH_USER_MODEL = 'ungdunggb.User'
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# app name :GroupBuyingEcommerceApp
CLIENT_ID = 'JP8d7Gi7bXqTskuexdkpLTxWLRbkR6tLFy89obmC'
CLIENT_SECRET = 'cx8h6ItGxDOkYzrnVjvO2IyOw9VX0CXhxkx2RVCDy6YhX0wOeO6azr5EKhGeEaO9iwNU6FMEqdjcOUM9FZNSBbUeHQQEkJw8AyHOja0UAvkUFmp3re2mXiOzXy3qUgUn'

# GRANT_TYPE UN_FING_SUPPORTED!!!!
# OAUTH2_PROVIDER = {
#     'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore'
# }

# id2: AfAgCqjiK3vHE5JPKNCYAf4pW7Xj1TN576vmcI2I
# secret2:Hf0vX606jNuqDWGNxeYvc8Da1aGsteGLTnXJbf0EEtLqYgivWhAiDdi417ksLGYT1MnbOCyMzsF57oxOJLP0n44fflUW4fqVmKFeop2a0t9Gan3MloEcewpsPHmv04I3